<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.jcaa</groupId>
    <artifactId>ejemplo-lipermi-imc</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>ejemplo-lipermi-servidor-imc</artifactId>
  <packaging>jar</packaging>
  <name>Paso 2 - Proyecto servidor</name>

  <dependencies>
    <dependency>
      <groupId>com.jcaa</groupId>
      <artifactId>ejemplo-lipermi-lib-imc</artifactId>
    </dependency>
    <dependency>
      <groupId>com.tascape.qa</groupId>
      <artifactId>lipermi</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <mainClass>com.jcaa.imc.rmi.servidor.Principal</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
